//
//  Map.h
//  Map
//
//  Created by Chris on 6/1/17.
//  Copyright © 2017 Def Con. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    MapResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    MapResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    MapResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    MapResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} MapResizingBehavior;

extern CGRect MapResizingBehaviorApply(MapResizingBehavior behavior, CGRect rect, CGRect target);


@interface Map : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas1WithFrame: (CGRect)targetFrame resizing: (MapResizingBehavior)resizing;

@end
